name: PostgreSQL Service Demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: npm install

    - name: Wait for DB
      run: |
        for i in {1..30}; do
          nc -z localhost 5432 && echo "DB is ready!" && break
          echo "Waiting for DB..."
          sleep 1
        done

    - run: npm test
      env:
        DB_HOST: localhost
        DB_USER: test
        DB_PASS: test
        DB_NAME: testdb
